"""Portfolio construction interfaces."""

from quant_research.portfolio.construction import PortfolioConstructor
from quant_research.portfolio.factor_portfolios import (
    CandidateFactor,
    FactorHealthConfig,
    RegimeConditionedFactorWeightConfig,
    build_composite_scores,
    build_factor_health_ensemble_schedule,
    build_factor_health_schedule,
    build_regime_conditioned_factor_weight_schedule,
    build_state_conditioned_factor_health_schedule,
    build_state_conditioned_factor_health_schedule_from_partitions,
    cap_factor_weights,
    factor_contribution_diagnostics,
    factor_combination_weights,
    load_candidate_factors,
    write_score_partitions,
)
from quant_research.portfolio.forecast_calibration import (
    ScoreForecastCalibrationConfig,
    apply_score_forecast_calibration,
    build_score_forecast_calibration,
    build_score_forecast_calibration_from_observations,
    build_score_forecast_calibration_from_partitions,
    score_forecast_calibration_observations,
)
from quant_research.portfolio.models import (
    PortfolioConfig,
    PortfolioConstructionResult,
)
from quant_research.portfolio.risk import (
    RiskConstraint,
    RollingRegimeGateConfig,
    build_rolling_regime_gate,
)
from quant_research.portfolio.t1 import apply_cn_t1_constraints
from quant_research.portfolio.allocator_registry import (
    AllocatorRegistry,
    AllocatorRegistryEntry,
    AllocatorRegistryIssue,
    AllocatorRegistryValidationReport,
    load_allocator_registry,
    render_allocator_registry_markdown,
    validate_allocator_registry,
    write_allocator_registry_report,
)
from quant_research.portfolio.allocator_monitoring import (
    AllocatorMonitoringReport,
    allocator_monitoring_history_row,
    allocator_monitoring_history_status,
    append_allocator_monitoring_history,
    generate_allocator_monitoring_report,
    render_allocator_monitoring_markdown,
    write_allocator_monitoring_report,
)

__all__ = [
    "AllocatorMonitoringReport",
    "AllocatorRegistry",
    "AllocatorRegistryEntry",
    "AllocatorRegistryIssue",
    "AllocatorRegistryValidationReport",
    "allocator_monitoring_history_row",
    "allocator_monitoring_history_status",
    "append_allocator_monitoring_history",
    "PortfolioConfig",
    "PortfolioConstructionResult",
    "PortfolioConstructor",
    "CandidateFactor",
    "FactorHealthConfig",
    "RegimeConditionedFactorWeightConfig",
    "RiskConstraint",
    "RollingRegimeGateConfig",
    "ScoreForecastCalibrationConfig",
    "apply_cn_t1_constraints",
    "apply_score_forecast_calibration",
    "build_composite_scores",
    "build_factor_health_ensemble_schedule",
    "build_factor_health_schedule",
    "build_regime_conditioned_factor_weight_schedule",
    "build_state_conditioned_factor_health_schedule",
    "build_state_conditioned_factor_health_schedule_from_partitions",
    "cap_factor_weights",
    "factor_contribution_diagnostics",
    "factor_combination_weights",
    "build_score_forecast_calibration",
    "build_score_forecast_calibration_from_observations",
    "build_score_forecast_calibration_from_partitions",
    "build_rolling_regime_gate",
    "generate_allocator_monitoring_report",
    "load_candidate_factors",
    "load_allocator_registry",
    "render_allocator_monitoring_markdown",
    "render_allocator_registry_markdown",
    "score_forecast_calibration_observations",
    "validate_allocator_registry",
    "write_allocator_monitoring_report",
    "write_allocator_registry_report",
    "write_score_partitions",
]
